import { NextResponse } from "next/server"

function futureDate(days: number, hours: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  date.setHours(hours, 0, 0, 0)
  return date.toISOString()
}


// ============================================
// UPDATE THESE EVENTS EVERY 1-2 WEEKS
// Go to terplink.umd.edu/events and pick
// 5-6 upcoming social/low-pressure events
// Last updated: July 18, 2026
// ============================================

export async function GET() {
  const events = [
    {
      id: "umb-wellness-001",
      title: "UMB Student Wellness Walk",
      description: "A casual morning walk for UMB students to connect, unwind, and get some fresh air between classes.",
      category: "outdoors",
      locationId: "loc-eppley",
      hostId: "system",
      capacity: 15,
      startTime: "2026-07-22T13:00:00.000Z",
      availabilityBlock: "weekday_morning",
      source: "org",
      status: "approved",
      universityId: "umb",
      cohort: "umb-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu",
    },
    {
      id: "terplink-12478027",
      title: "Figure Drawing Workshop",
      description: "Join Studio A for a live, clothed model figure drawing session with multiple timed sessions. All supplies provided — no experience needed.",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 20,
      startTime: "2026-07-20T22:30:00.000Z",
      availabilityBlock: "weekday_evening",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12478027",
    },
    {
      id: "terplink-12467869",
      title: "Community Learning Garden Volunteer Hours",
      description: "Join us in the Community Learning Garden for fresh air, good vibes, and garden therapy. No experience needed. Located between Eppley and the School of Public Health.",
      category: "volunteering",
      locationId: "loc-eppley",
      hostId: "system",
      capacity: 20,
      startTime: "2026-07-21T14:00:00.000Z",
      availabilityBlock: "weekday_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12467869",
    },
    {
      id: "terplink-12510045",
      title: "Cozy Conversations: Heart & Harm",
      description: "Join the Memorial Chapel for free lunch and conversation about religious and spiritual practice, wellness, and mental health. Spots are limited — great for an honest, low-key chat.",
      category: "faith",
      locationId: "loc-mckeldin",
      hostId: "system",
      capacity: 15,
      startTime: "2026-07-22T16:00:00.000Z",
      availabilityBlock: "weekday_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "small",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12510045",
    },
    {
      id: "terplink-12467873",
      title: "Community Learning Garden Volunteer Hours",
      description: "Saturday morning garden therapy — fresh air, good vibes, no experience needed. SSL hours available. Located between Eppley and the School of Public Health.",
      category: "volunteering",
      locationId: "loc-eppley",
      hostId: "system",
      capacity: 20,
      startTime: "2026-07-25T13:00:00.000Z",
      availabilityBlock: "weekend_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12467873",
    },
    {
      id: "terplink-12437391",
      title: "Terrapin Anime Society: Otakon 2026",
      description: "Join UMD students at Otakon — one of the largest anime and Japanese pop culture conventions in the US, right in Washington DC. Panels, cosplay, artist alleys, and more.",
      category: "hangout",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 30,
      startTime: "2026-07-31T12:00:00.000Z",
      availabilityBlock: "weekend_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12437391",
    },
    {
      id: "terplink-12478035",
      title: "Gnome Handbuilding",
      description: "Create a ceramic gnome in Studio A's pottery studio! Gnomes will be fired and ready within 3 weeks. Wear clothes you're comfortable getting dirty.",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 15,
      startTime: "2026-08-01T17:00:00.000Z",
      availabilityBlock: "weekend_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12478035",
    },
    {
      id: "terplink-12478030",
      title: "Play in Clay",
      description: "Experiment with clay and the pottery wheel! Learn to wedge, center, and pull a cylinder. Drop in, first-come first-serve. Wear clothes you're comfortable getting dirty.",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 20,
      startTime: "2026-08-08T17:00:00.000Z",
      availabilityBlock: "weekend_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12478030",
    },
    {
      id: "terplink-12472469",
      title: "STAMP Garden Club Event",
      description: "Help care for the Chef's Garden with weeding and watering. Meet near the clock at Stamp. No experience necessary, SSL hours available, gloves and tools provided.",
      category: "volunteering",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 15,
      startTime: "2026-08-19T13:00:00.000Z",
      availabilityBlock: "weekday_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12472469",
    },
    {
      id: "terplink-12501410",
      title: "STAMP Extravaganza",
      description: "Kick off your first night on campus! Hypnotist, game show, bingo, karaoke, scavenger hunt, glow bowling, and prizes. Free food and fun until midnight — perfect for meeting new people.",
      category: "hangout",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 200,
      startTime: "2026-08-29T01:00:00.000Z",
      availabilityBlock: "weekend_evening",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12501410",
    },
    {
      id: "terplink-12483338",
      title: "SEE Presents: Moonlit Music",
      description: "An outdoor evening music event at the Nyumburu Amphitheater. A great low-key way to unwind and meet people under the stars.",
      category: "arts",
      locationId: "loc-hornbake",
      hostId: "system",
      capacity: 100,
      startTime: "2026-08-30T01:00:00.000Z",
      availabilityBlock: "weekend_evening",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12483338",
    },
    {
      id: "terplink-12389371",
      title: "stART — Art Volunteering with Kids",
      description: "Help elementary-aged kids from the College Park community with art projects. Meet at the UMD Memorial Chapel at 2pm to carpool. Not religious — focused on art and mentorship.",
      category: "volunteering",
      locationId: "loc-mckeldin",
      hostId: "system",
      capacity: 15,
      startTime: "2026-09-01T19:00:00.000Z",
      availabilityBlock: "weekday_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12389371",
    },
  ]

  return NextResponse.json({ events })
}