import { NextResponse } from "next/server"

function futureDate(days: number, hours: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  date.setHours(hours, 0, 0, 0)
  return date.toISOString()
}
export async function GET() {
  const events = [
    {
      id: "terplink-12467862",
      title: "Community Learning Garden Volunteer Hours",
      description: "Join us in the Community Learning Garden for fresh air, good vibes, and garden therapy. No experience needed — summer hours. Located between Eppley and the School of Public Health.",
      category: "volunteering",
      locationId: "loc-eppley",
      hostId: "system",
      capacity: 20,
      startTime: "2026-07-02T14:00:00.000Z",
      availabilityBlock: "weekday_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12467862",
    },
    {
      id: "terplink-12406210",
      title: "Arranging Workshop",
      description: "An interactive workshop walking you through the a cappella arranging process — from selecting a song to building harmonies and assigning vocal parts. Great for singers and curious listeners alike.",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 30,
      startTime: "2026-07-05T16:00:00.000Z",
      availabilityBlock: "weekend_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12406210",
    },
    {
      id: "terplink-12478017",
      title: "Outdoor Painting at the Memorial Chapel",
      description: "Looking for a way to relax, unwind, and create? Join Studio A at the Memorial Chapel to make a painting in the Chapel gardens. All supplies provided.",
      category: "arts",
      locationId: "loc-tawes",
      hostId: "system",
      capacity: 15,
      startTime: "2026-07-09T17:00:00.000Z",
      availabilityBlock: "weekday_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12478017",
    },
    {
      id: "terplink-12474998",
      title: "Bee Wall Pollinator Garden Volunteer Hours",
      description: "Join us at Dwelling: Paint Branch Creek to care for its pollinator garden. No experience necessary, SSL hours available. Gloves and tools provided.",
      category: "volunteering",
      locationId: "loc-eppley",
      hostId: "system",
      capacity: 20,
      startTime: "2026-07-08T14:00:00.000Z",
      availabilityBlock: "weekday_morning",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12474998",
    },
    {
      id: "terplink-12498047",
      title: "Opening Reception: Basement",
      description: "An exhibition celebrating the hidden lives of strangers we take for granted. Features 12 artists curated by Sydney Feurer. Free and open to the public. Free food!",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 50,
      startTime: "2026-07-13T21:00:00.000Z",
      availabilityBlock: "weekday_evening",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12498047",
    },
    {
      id: "terplink-12478030",
      title: "Play in Clay",
      description: "Experiment with clay and the pottery wheel! Learn how to wedge, center, and pull a cylinder. Drop in, first-come first-serve. Wear clothes you're comfortable getting dirty.",
      category: "arts",
      locationId: "loc-stamp",
      hostId: "system",
      capacity: 20,
      startTime: "2026-08-08T17:00:00.000Z",
      availabilityBlock: "weekend_afternoon",
      source: "org",
      status: "approved",
      universityId: "umd",
      cohort: "umd-pilot",
      comfortSize: "either",
      safetyPreference: "none",
      createdAt: new Date().toISOString(),
      terpLinkUrl: "https://terplink.umd.edu/event/12478030",
    },
  ]

  return NextResponse.json({ events })
}